### ISSUE TITLE
The package should install the correct version of Ansible

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#132]
Since the deb package relies on a newer version of Ansible being installed, the package should install that version for the admin.

Alternatively, you can provide documentation on installing the version of Ansible we require.

**Comment by thatarchguy** [comment]
I have this fixed in this commit on ft-database_migrations-125:
https://github.com/StackFocus/PostMaster/commit/561573512e49238955d71bd37ab45e2fee503437

I basically pip install ansible globally, since the package is way out of date for Ubuntu 14. We are still inbetween Ubuntu versions so I'm just making it work for both for the time being.

**Comment by PrahlM93** [comment]
#138 handles this.
