### ISSUE TITLE
Add version function to manage.py

### ISSUE THREAD

**Issue by PrahlM93** [StackFocus/PostMaster#155]
Currently, there is no easy way to tell what version of PostMaster you are on. A user should be able to run `python manage.py version` to get the current PostMaster version. Travis should update this value to match the GitHub tag. The [TRAVIS_TAG](https://docs.travis-ci.com/user/environment-variables/) should work well for this.

**Comment by thatarchguy** [comment]
I support having the version in the manage.py cli. We have to inject the version in to the release script and the changelog as well. Maybe just have it be manual by pull-request when we want to cut a release? I wouldn't be dependent on travis since people can get Postmaster by git clone / download zip / deb package.

**Comment by PrahlM93** [comment]
What I meant by Travis' role in this is that when we cut a new release via creating a git tag, Travis should change the version in manage.py automatically according to the git tag. I now realize this wouldn't work because the changes made by Travis would not be reflected in the tagged version, and we'd have to somehow give Travis to commit directly to master.

With that being said, I agree with a manual PR.
